### ISSUE TITLE
.env overrides don't work 

### ISSUE THREAD

**Issue by imakeinterfaces** [envkey/envkey-webpack-plugin#2]
If overrides are present in `.env` process.env has missing properties.  

This can be reproduced by adding values after the envkey token is defined in `.env`. Adding breakpoints in the generated webpack code shows an incomplete version of the object stored in envkey. Its contents don't match `env.example`, `.env`, or the results shown in the envkey app.

**Comment by danenania** [comment]
Thanks @imakeinterfaces - this should now be fixed in 1.1.1
